var hierarchy =
[
    [ "AdministradorCandidatos", "classAdministradorCandidatos.html", null ],
    [ "rocksdb::BackupableDBOptions", "structrocksdb_1_1BackupableDBOptions.html", null ],
    [ "rocksdb::BackupEngine", "classrocksdb_1_1BackupEngine.html", null ],
    [ "rocksdb::BackupEngineReadOnly", "classrocksdb_1_1BackupEngineReadOnly.html", null ],
    [ "rocksdb::BackupInfo", "structrocksdb_1_1BackupInfo.html", null ],
    [ "rocksdb::BackupStatistics", "classrocksdb_1_1BackupStatistics.html", null ],
    [ "BaseDeDatos", "classBaseDeDatos.html", null ],
    [ "rocksdb::BatchResult", "structrocksdb_1_1BatchResult.html", null ],
    [ "rocksdb::BlockBasedTableOptions", "structrocksdb_1_1BlockBasedTableOptions.html", null ],
    [ "rocksdb::BlockBasedTablePropertyNames", "structrocksdb_1_1BlockBasedTablePropertyNames.html", null ],
    [ "rocksdb::spatial::BoundingBox< T >", "structrocksdb_1_1spatial_1_1BoundingBox.html", null ],
    [ "rocksdb::spatial::BoundingBox< double >", "structrocksdb_1_1spatial_1_1BoundingBox.html", null ],
    [ "rocksdb::Cache", "classrocksdb_1_1Cache.html", null ],
    [ "Candidatos", "classCandidatos.html", null ],
    [ "char64long16", "unionchar64long16.html", null ],
    [ "Json::CharReader", "classJson_1_1CharReader.html", [
      [ "Json::OurCharReader", "classJson_1_1OurCharReader.html", null ]
    ] ],
    [ "rocksdb::Checkpoint", "classrocksdb_1_1Checkpoint.html", null ],
    [ "rocksdb::Cleanable", "classrocksdb_1_1Cleanable.html", [
      [ "rocksdb::Iterator", "classrocksdb_1_1Iterator.html", null ]
    ] ],
    [ "rocksdb::Cleanable::Cleanup", "structrocksdb_1_1Cleanable_1_1Cleanup.html", null ],
    [ "ClienteDelSharedServer", "classClienteDelSharedServer.html", null ],
    [ "rocksdb::ColumnFamilyDescriptor", "structrocksdb_1_1ColumnFamilyDescriptor.html", null ],
    [ "rocksdb::ColumnFamilyHandle", "classrocksdb_1_1ColumnFamilyHandle.html", null ],
    [ "rocksdb::ColumnFamilyMetaData", "structrocksdb_1_1ColumnFamilyMetaData.html", null ],
    [ "rocksdb::ColumnFamilyOptions", "structrocksdb_1_1ColumnFamilyOptions.html", [
      [ "rocksdb::Options", "structrocksdb_1_1Options.html", null ]
    ] ],
    [ "Json::CommentStyle", "structJson_1_1CommentStyle.html", null ],
    [ "rocksdb::CompactionFilter", "classrocksdb_1_1CompactionFilter.html", null ],
    [ "rocksdb::CompactionFilterContext", "structrocksdb_1_1CompactionFilterContext.html", null ],
    [ "rocksdb::CompactionFilterFactory", "classrocksdb_1_1CompactionFilterFactory.html", null ],
    [ "rocksdb::CompactionJobInfo", "structrocksdb_1_1CompactionJobInfo.html", null ],
    [ "rocksdb::CompactionJobStats", "structrocksdb_1_1CompactionJobStats.html", null ],
    [ "rocksdb::CompactionOptions", "structrocksdb_1_1CompactionOptions.html", null ],
    [ "rocksdb::CompactionOptionsFIFO", "structrocksdb_1_1CompactionOptionsFIFO.html", null ],
    [ "rocksdb::CompactionOptionsUniversal", "classrocksdb_1_1CompactionOptionsUniversal.html", null ],
    [ "rocksdb::CompactRangeOptions", "structrocksdb_1_1CompactRangeOptions.html", null ],
    [ "rocksdb::Comparator", "classrocksdb_1_1Comparator.html", null ],
    [ "rocksdb::CompressionOptions", "structrocksdb_1_1CompressionOptions.html", null ],
    [ "rocksdb::constexpr_max< A, B >", "structrocksdb_1_1constexpr__max.html", null ],
    [ "rocksdb::CompactionFilter::Context", "structrocksdb_1_1CompactionFilter_1_1Context.html", null ],
    [ "rocksdb::TablePropertiesCollectorFactory::Context", "structrocksdb_1_1TablePropertiesCollectorFactory_1_1Context.html", null ],
    [ "Conversaciones", "classConversaciones.html", null ],
    [ "CreatorServicio", "classCreatorServicio.html", [
      [ "CreatorBusquedaCandidato", "classCreatorBusquedaCandidato.html", null ],
      [ "CreatorChat", "classCreatorChat.html", null ],
      [ "CreatorEliminacion", "classCreatorEliminacion.html", null ],
      [ "CreatorLogin", "classCreatorLogin.html", null ],
      [ "CreatorModificarFoto", "classCreatorModificarFoto.html", null ],
      [ "CreatorRegistro", "classCreatorRegistro.html", null ],
      [ "CreatorServicioMensajes", "classCreatorServicioMensajes.html", null ],
      [ "CreatorVotacion", "classCreatorVotacion.html", null ]
    ] ],
    [ "CredencialesDeUsuarios", "classCredencialesDeUsuarios.html", null ],
    [ "cs_base64_ctx", "structcs__base64__ctx.html", null ],
    [ "cs_sha1_ctx", "structcs__sha1__ctx.html", null ],
    [ "ctl_msg", "structctl__msg.html", null ],
    [ "rocksdb::CuckooTableOptions", "structrocksdb_1_1CuckooTableOptions.html", null ],
    [ "rocksdb::CuckooTablePropertyNames", "structrocksdb_1_1CuckooTablePropertyNames.html", null ],
    [ "rocksdb::Cursor", "classrocksdb_1_1Cursor.html", null ],
    [ "rocksdb::spatial::Cursor", "classrocksdb_1_1spatial_1_1Cursor.html", null ],
    [ "datosDeSesion", "structdatosDeSesion.html", null ],
    [ "rocksdb::DB", "classrocksdb_1_1DB.html", [
      [ "rocksdb::StackableDB", "classrocksdb_1_1StackableDB.html", [
        [ "rocksdb::BackupableDB", "classrocksdb_1_1BackupableDB.html", null ],
        [ "rocksdb::DBWithTTL", "classrocksdb_1_1DBWithTTL.html", null ],
        [ "rocksdb::DocumentDB", "classrocksdb_1_1DocumentDB.html", null ],
        [ "rocksdb::GeoDB", "classrocksdb_1_1GeoDB.html", null ],
        [ "rocksdb::spatial::SpatialDB", "classrocksdb_1_1spatial_1_1SpatialDB.html", null ],
        [ "rocksdb::TransactionDB", "classrocksdb_1_1TransactionDB.html", null ]
      ] ]
    ] ],
    [ "rocksdb::DbDumpTool", "classrocksdb_1_1DbDumpTool.html", null ],
    [ "rocksdb::DBOptions", "structrocksdb_1_1DBOptions.html", [
      [ "rocksdb::Options", "structrocksdb_1_1Options.html", null ]
    ] ],
    [ "rocksdb::DbPath", "structrocksdb_1_1DbPath.html", null ],
    [ "rocksdb::DbUndumpTool", "classrocksdb_1_1DbUndumpTool.html", null ],
    [ "rocksdb::Directory", "classrocksdb_1_1Directory.html", null ],
    [ "rocksdb::DocumentDBOptions", "structrocksdb_1_1DocumentDBOptions.html", null ],
    [ "rocksdb::DumpOptions", "structrocksdb_1_1DumpOptions.html", null ],
    [ "rocksdb::Env", "classrocksdb_1_1Env.html", [
      [ "rocksdb::EnvWrapper", "classrocksdb_1_1EnvWrapper.html", [
        [ "rocksdb::EnvMirror", "classrocksdb_1_1EnvMirror.html", null ]
      ] ]
    ] ],
    [ "rocksdb::EnvOptions", "structrocksdb_1_1EnvOptions.html", null ],
    [ "Estadisticas", "structEstadisticas.html", null ],
    [ "EstadisticasCandidatos", "classEstadisticasCandidatos.html", null ],
    [ "rocksdb::EventListener", "classrocksdb_1_1EventListener.html", null ],
    [ "exception", null, [
      [ "Json::Exception", "classJson_1_1Exception.html", [
        [ "Json::LogicError", "classJson_1_1LogicError.html", null ],
        [ "Json::RuntimeError", "classJson_1_1RuntimeError.html", null ]
      ] ]
    ] ],
    [ "rocksdb::ExternalSstFileInfo", "structrocksdb_1_1ExternalSstFileInfo.html", null ],
    [ "rocksdb::ExternalSstFilePropertyNames", "structrocksdb_1_1ExternalSstFilePropertyNames.html", null ],
    [ "Json::CharReader::Factory", "classJson_1_1CharReader_1_1Factory.html", [
      [ "Json::CharReaderBuilder", "classJson_1_1CharReaderBuilder.html", null ]
    ] ],
    [ "Json::StreamWriter::Factory", "classJson_1_1StreamWriter_1_1Factory.html", [
      [ "Json::StreamWriterBuilder", "classJson_1_1StreamWriterBuilder.html", null ]
    ] ],
    [ "FactoryServicios", "classFactoryServicios.html", null ],
    [ "fbson::FbsonWriterT< T >", "classfbson_1_1FbsonWriterT.html", null ],
    [ "Json::Features", "classJson_1_1Features.html", null ],
    [ "rocksdb::spatial::FeatureSet", "classrocksdb_1_1spatial_1_1FeatureSet.html", null ],
    [ "rocksdb::Env::FileAttributes", "structrocksdb_1_1Env_1_1FileAttributes.html", null ],
    [ "rocksdb::FileLock", "classrocksdb_1_1FileLock.html", [
      [ "rocksdb::EnvMirror::FileLockMirror", "classrocksdb_1_1EnvMirror_1_1FileLockMirror.html", null ]
    ] ],
    [ "rocksdb::FilterBitsBuilder", "classrocksdb_1_1FilterBitsBuilder.html", null ],
    [ "rocksdb::FilterBitsReader", "classrocksdb_1_1FilterBitsReader.html", null ],
    [ "rocksdb::FilterPolicy", "classrocksdb_1_1FilterPolicy.html", null ],
    [ "rocksdb::FlushBlockPolicy", "classrocksdb_1_1FlushBlockPolicy.html", null ],
    [ "rocksdb::FlushBlockPolicyFactory", "classrocksdb_1_1FlushBlockPolicyFactory.html", [
      [ "rocksdb::FlushBlockBySizePolicyFactory", "classrocksdb_1_1FlushBlockBySizePolicyFactory.html", null ]
    ] ],
    [ "rocksdb::FlushJobInfo", "structrocksdb_1_1FlushJobInfo.html", null ],
    [ "rocksdb::FlushOptions", "structrocksdb_1_1FlushOptions.html", null ],
    [ "frozen", "structfrozen.html", null ],
    [ "rocksdb::GeoDBOptions", "structrocksdb_1_1GeoDBOptions.html", null ],
    [ "rocksdb::GeoIterator", "classrocksdb_1_1GeoIterator.html", null ],
    [ "rocksdb::GeoObject", "classrocksdb_1_1GeoObject.html", null ],
    [ "rocksdb::GeoPosition", "classrocksdb_1_1GeoPosition.html", null ],
    [ "rocksdb::Cache::Handle", "structrocksdb_1_1Cache_1_1Handle.html", null ],
    [ "rocksdb::WriteBatch::Handler", "classrocksdb_1_1WriteBatch_1_1Handler.html", null ],
    [ "rocksdb::HistogramData", "structrocksdb_1_1HistogramData.html", null ],
    [ "http_message", "structhttp__message.html", null ],
    [ "rocksdb::ImmutableCFOptions", "structrocksdb_1_1ImmutableCFOptions.html", null ],
    [ "rocksdb::DocumentDB::IndexDescriptor", "structrocksdb_1_1DocumentDB_1_1IndexDescriptor.html", null ],
    [ "Interes", "classInteres.html", null ],
    [ "rocksdb::IOStatsContext", "structrocksdb_1_1IOStatsContext.html", null ],
    [ "rocksdb::MemTableRep::Iterator", "classrocksdb_1_1MemTableRep_1_1Iterator.html", null ],
    [ "rocksdb::spatial::FeatureSet::iterator", "classrocksdb_1_1spatial_1_1FeatureSet_1_1iterator.html", null ],
    [ "json_token", "structjson__token.html", null ],
    [ "rocksdb::JSONDocument", "classrocksdb_1_1JSONDocument.html", null ],
    [ "rocksdb::JSONDocumentBuilder", "classrocksdb_1_1JSONDocumentBuilder.html", null ],
    [ "JsonValor", "classJsonValor.html", [
      [ "JsonArray", "classJsonArray.html", null ],
      [ "JsonObject", "classJsonObject.html", null ]
    ] ],
    [ "rocksdb::MemTableRep::KeyComparator", "classrocksdb_1_1MemTableRep_1_1KeyComparator.html", null ],
    [ "rocksdb::LDBOptions", "structrocksdb_1_1LDBOptions.html", null ],
    [ "rocksdb::LDBTool", "classrocksdb_1_1LDBTool.html", null ],
    [ "rocksdb::LevelDBOptions", "structrocksdb_1_1LevelDBOptions.html", null ],
    [ "rocksdb::LevelMetaData", "structrocksdb_1_1LevelMetaData.html", null ],
    [ "ListadoDeIntereses", "classListadoDeIntereses.html", null ],
    [ "ListadoDeUsuarios", "classListadoDeUsuarios.html", null ],
    [ "rocksdb::LogFile", "classrocksdb_1_1LogFile.html", null ],
    [ "rocksdb::Logger", "classrocksdb_1_1Logger.html", null ],
    [ "rocksdb::ManagedSnapshot", "classrocksdb_1_1ManagedSnapshot.html", null ],
    [ "ManejadorDeConexiones", "classManejadorDeConexiones.html", null ],
    [ "mbuf", "structmbuf.html", null ],
    [ "MD5Context", "structMD5Context.html", null ],
    [ "rocksdb::MemoryUtil", "classrocksdb_1_1MemoryUtil.html", null ],
    [ "rocksdb::MemTableRep", "classrocksdb_1_1MemTableRep.html", null ],
    [ "rocksdb::MemTableRepFactory", "classrocksdb_1_1MemTableRepFactory.html", [
      [ "rocksdb::SkipListFactory", "classrocksdb_1_1SkipListFactory.html", null ],
      [ "rocksdb::VectorRepFactory", "classrocksdb_1_1VectorRepFactory.html", null ]
    ] ],
    [ "MensajeHTTP", "classMensajeHTTP.html", [
      [ "MensajeHTTPReply", "classMensajeHTTPReply.html", null ],
      [ "MensajeHTTPRequest", "classMensajeHTTPRequest.html", [
        [ "MensajeHTTPRequestGCM", "classMensajeHTTPRequestGCM.html", null ]
      ] ]
    ] ],
    [ "Mensajero", "classMensajero.html", null ],
    [ "Mensajes", "classMensajes.html", null ],
    [ "rocksdb::MergeOperator", "classrocksdb_1_1MergeOperator.html", [
      [ "rocksdb::AssociativeMergeOperator", "classrocksdb_1_1AssociativeMergeOperator.html", null ]
    ] ],
    [ "mg_add_sock_opts", "structmg__add__sock__opts.html", null ],
    [ "mg_bind_opts", "structmg__bind__opts.html", null ],
    [ "mg_cgi_env_block", "structmg__cgi__env__block.html", null ],
    [ "mg_connect_opts", "structmg__connect__opts.html", null ],
    [ "mg_connection", "structmg__connection.html", null ],
    [ "mg_dns_header", "structmg__dns__header.html", null ],
    [ "mg_dns_message", "structmg__dns__message.html", null ],
    [ "mg_dns_resource_record", "structmg__dns__resource__record.html", null ],
    [ "mg_http_multipart_part", "structmg__http__multipart__part.html", null ],
    [ "mg_http_proto_data", "structmg__http__proto__data.html", null ],
    [ "mg_http_proto_data_cgi", "structmg__http__proto__data__cgi.html", null ],
    [ "mg_http_proto_data_chuncked", "structmg__http__proto__data__chuncked.html", null ],
    [ "mg_http_proto_data_file", "structmg__http__proto__data__file.html", null ],
    [ "mg_mgr", "structmg__mgr.html", null ],
    [ "mg_mqtt_message", "structmg__mqtt__message.html", null ],
    [ "mg_mqtt_topic_expression", "structmg__mqtt__topic__expression.html", null ],
    [ "mg_resolve_async_opts", "structmg__resolve__async__opts.html", null ],
    [ "mg_resolve_async_request", "structmg__resolve__async__request.html", null ],
    [ "mg_rpc_error", "structmg__rpc__error.html", null ],
    [ "mg_rpc_reply", "structmg__rpc__reply.html", null ],
    [ "mg_rpc_request", "structmg__rpc__request.html", null ],
    [ "mg_send_mqtt_handshake_opts", "structmg__send__mqtt__handshake__opts.html", null ],
    [ "mg_serve_http_opts", "structmg__serve__http__opts.html", null ],
    [ "mg_str", "structmg__str.html", null ],
    [ "rocksdb::OptimisticTransactionDB", "classrocksdb_1_1OptimisticTransactionDB.html", null ],
    [ "rocksdb::OptimisticTransactionOptions", "structrocksdb_1_1OptimisticTransactionOptions.html", null ],
    [ "Json::OurFeatures", "classJson_1_1OurFeatures.html", null ],
    [ "Json::OurReader", "classJson_1_1OurReader.html", null ],
    [ "Pareja", "classPareja.html", null ],
    [ "Json::Path", "classJson_1_1Path.html", null ],
    [ "Json::PathArgument", "classJson_1_1PathArgument.html", null ],
    [ "rocksdb::PerfContext", "structrocksdb_1_1PerfContext.html", null ],
    [ "rocksdb::PlainTableOptions", "structrocksdb_1_1PlainTableOptions.html", null ],
    [ "rocksdb::PlainTablePropertyNames", "structrocksdb_1_1PlainTablePropertyNames.html", null ],
    [ "rocksdb::DB::Properties", "structrocksdb_1_1DB_1_1Properties.html", null ],
    [ "rocksdb::RandomAccessFile", "classrocksdb_1_1RandomAccessFile.html", null ],
    [ "rocksdb::Range", "structrocksdb_1_1Range.html", null ],
    [ "rocksdb::RateLimiter", "classrocksdb_1_1RateLimiter.html", null ],
    [ "Json::Reader", "classJson_1_1Reader.html", null ],
    [ "rocksdb::TransactionLogIterator::ReadOptions", "structrocksdb_1_1TransactionLogIterator_1_1ReadOptions.html", null ],
    [ "rocksdb::ReadOptions", "structrocksdb_1_1ReadOptions.html", null ],
    [ "Json::SecureAllocator< T >::rebind< U >", "structJson_1_1SecureAllocator_1_1rebind.html", null ],
    [ "RespuestaDelServicio", "classRespuestaDelServicio.html", [
      [ "RespuestaDeLaBusqueda", "classRespuestaDeLaBusqueda.html", null ],
      [ "RespuestaDeLaVotacion", "classRespuestaDeLaVotacion.html", null ],
      [ "RespuestaDelChat", "classRespuestaDelChat.html", null ],
      [ "RespuestaDelLogin", "classRespuestaDelLogin.html", null ],
      [ "RespuestaDelRegistro", "classRespuestaDelRegistro.html", null ],
      [ "RespuestaEliminacion", "classRespuestaEliminacion.html", null ],
      [ "RespuestaMensajes", "classRespuestaMensajes.html", null ],
      [ "RespuestaModificarFoto", "classRespuestaModificarFoto.html", null ],
      [ "RespuestaServicioInexistente", "classRespuestaServicioInexistente.html", null ]
    ] ],
    [ "rocksdb::RestoreBackupableDB", "classrocksdb_1_1RestoreBackupableDB.html", null ],
    [ "rocksdb::RestoreOptions", "structrocksdb_1_1RestoreOptions.html", null ],
    [ "Json::SecureAllocator< T >", "classJson_1_1SecureAllocator.html", null ],
    [ "rocksdb::SequentialFile", "classrocksdb_1_1SequentialFile.html", null ],
    [ "Servicio", "classServicio.html", [
      [ "ServicioBusquedaCandidatos", "classServicioBusquedaCandidatos.html", null ],
      [ "ServicioChat", "classServicioChat.html", null ],
      [ "ServicioEliminarUsuario", "classServicioEliminarUsuario.html", null ],
      [ "ServicioInexistente", "classServicioInexistente.html", null ],
      [ "servicioLogin", "classservicioLogin.html", null ],
      [ "ServicioMensajes", "classServicioMensajes.html", null ],
      [ "ServicioModificarFoto", "classServicioModificarFoto.html", null ],
      [ "servicioRegistro", "classservicioRegistro.html", null ],
      [ "ServicioVotacion", "classServicioVotacion.html", null ]
    ] ],
    [ "Servidor", "classServidor.html", null ],
    [ "SesionesDeUsuarios", "classSesionesDeUsuarios.html", null ],
    [ "SharedDataBase", "classSharedDataBase.html", null ],
    [ "rocksdb::Slice", "classrocksdb_1_1Slice.html", null ],
    [ "rocksdb::SliceFormatter", "classrocksdb_1_1SliceFormatter.html", null ],
    [ "rocksdb::SliceParts", "structrocksdb_1_1SliceParts.html", null ],
    [ "rocksdb::SliceTransform", "classrocksdb_1_1SliceTransform.html", null ],
    [ "rocksdb::Snapshot", "classrocksdb_1_1Snapshot.html", null ],
    [ "socket_address", "unionsocket__address.html", null ],
    [ "rocksdb::spatial::SpatialDBOptions", "structrocksdb_1_1spatial_1_1SpatialDBOptions.html", null ],
    [ "rocksdb::spatial::SpatialIndexOptions", "structrocksdb_1_1spatial_1_1SpatialIndexOptions.html", null ],
    [ "rocksdb::SSTDumpTool", "classrocksdb_1_1SSTDumpTool.html", null ],
    [ "rocksdb::SstFileManager", "classrocksdb_1_1SstFileManager.html", null ],
    [ "rocksdb::SstFileMetaData", "structrocksdb_1_1SstFileMetaData.html", [
      [ "rocksdb::LiveFileMetaData", "structrocksdb_1_1LiveFileMetaData.html", null ]
    ] ],
    [ "rocksdb::SstFileWriter", "classrocksdb_1_1SstFileWriter.html", null ],
    [ "Json::StaticString", "classJson_1_1StaticString.html", null ],
    [ "rocksdb::Statistics", "classrocksdb_1_1Statistics.html", null ],
    [ "rocksdb::Status", "classrocksdb_1_1Status.html", null ],
    [ "Json::StreamWriter", "classJson_1_1StreamWriter.html", [
      [ "Json::BuiltStyledStreamWriter", "structJson_1_1BuiltStyledStreamWriter.html", null ]
    ] ],
    [ "StringUtil", "classStringUtil.html", null ],
    [ "Json::OurReader::StructuredError", "structJson_1_1OurReader_1_1StructuredError.html", null ],
    [ "Json::Reader::StructuredError", "structJson_1_1Reader_1_1StructuredError.html", null ],
    [ "Json::StyledStreamWriter", "classJson_1_1StyledStreamWriter.html", null ],
    [ "rocksdb::TableFactory", "classrocksdb_1_1TableFactory.html", null ],
    [ "rocksdb::TableFileCreationInfo", "structrocksdb_1_1TableFileCreationInfo.html", null ],
    [ "rocksdb::TableFileDeletionInfo", "structrocksdb_1_1TableFileDeletionInfo.html", null ],
    [ "rocksdb::TableProperties", "structrocksdb_1_1TableProperties.html", null ],
    [ "rocksdb::TablePropertiesCollector", "classrocksdb_1_1TablePropertiesCollector.html", null ],
    [ "rocksdb::TablePropertiesCollectorFactory", "classrocksdb_1_1TablePropertiesCollectorFactory.html", null ],
    [ "rocksdb::TablePropertiesNames", "structrocksdb_1_1TablePropertiesNames.html", null ],
    [ "rocksdb::ThreadStatus", "structrocksdb_1_1ThreadStatus.html", null ],
    [ "rocksdb::Transaction", "classrocksdb_1_1Transaction.html", null ],
    [ "rocksdb::TransactionDBCondVar", "classrocksdb_1_1TransactionDBCondVar.html", null ],
    [ "rocksdb::TransactionDBMutex", "classrocksdb_1_1TransactionDBMutex.html", null ],
    [ "rocksdb::TransactionDBMutexFactory", "classrocksdb_1_1TransactionDBMutexFactory.html", null ],
    [ "rocksdb::TransactionDBOptions", "structrocksdb_1_1TransactionDBOptions.html", null ],
    [ "rocksdb::TransactionLogIterator", "classrocksdb_1_1TransactionLogIterator.html", null ],
    [ "rocksdb::TransactionNotifier", "classrocksdb_1_1TransactionNotifier.html", null ],
    [ "rocksdb::TransactionOptions", "structrocksdb_1_1TransactionOptions.html", null ],
    [ "rocksdb::UndumpOptions", "structrocksdb_1_1UndumpOptions.html", null ],
    [ "Usuario", "classUsuario.html", null ],
    [ "rocksdb::UtilityDB", "classrocksdb_1_1UtilityDB.html", null ],
    [ "Json::Value", "classJson_1_1Value.html", null ],
    [ "Json::ValueIteratorBase", "classJson_1_1ValueIteratorBase.html", [
      [ "Json::ValueConstIterator", "classJson_1_1ValueConstIterator.html", null ],
      [ "Json::ValueIterator", "classJson_1_1ValueIterator.html", null ]
    ] ],
    [ "rocksdb::spatial::Variant", "structrocksdb_1_1spatial_1_1Variant.html", null ],
    [ "rocksdb::WalFilter", "classrocksdb_1_1WalFilter.html", null ],
    [ "rocksdb::WBWIIterator", "classrocksdb_1_1WBWIIterator.html", null ],
    [ "websocket_message", "structwebsocket__message.html", null ],
    [ "rocksdb::WritableFile", "classrocksdb_1_1WritableFile.html", [
      [ "rocksdb::WritableFileWrapper", "classrocksdb_1_1WritableFileWrapper.html", null ]
    ] ],
    [ "rocksdb::WriteBatchBase", "classrocksdb_1_1WriteBatchBase.html", [
      [ "rocksdb::WriteBatch", "classrocksdb_1_1WriteBatch.html", null ],
      [ "rocksdb::WriteBatchWithIndex", "classrocksdb_1_1WriteBatchWithIndex.html", null ]
    ] ],
    [ "rocksdb::WriteEntry", "structrocksdb_1_1WriteEntry.html", null ],
    [ "rocksdb::WriteOptions", "structrocksdb_1_1WriteOptions.html", null ],
    [ "Json::Writer", "classJson_1_1Writer.html", [
      [ "Json::FastWriter", "classJson_1_1FastWriter.html", null ],
      [ "Json::StyledWriter", "classJson_1_1StyledWriter.html", null ]
    ] ],
    [ "ws_mask_ctx", "structws__mask__ctx.html", null ]
];