
language: c++

notifications:
  email:
    - segui.joaquin@gmail.com
    # diegofk26@gmail.com
   # Mail Seba
    - juanmafc25@gmail.com

sudo: required
dist: trusty

before_install:
#Dependencias RocksDB
install:
- pip install --upgrade pip
- pip install -H requests
- sh ./instalar_dependenciasTravis.sh


script:
- cd Appserver
- mkdir build
- cd build
- cmake ..
- make
- cd ../Test
- ./correr_pruebas_API.sh
- sh ./correrUnitTests.sh

