sudo: required
dist: trusty

language: c++

install:
#  - sudo -H pip install requests
  - sh ./instalar_dependenciasTravis.sh

script:
#instalo requests y corro una prueba minima
- cd Appserver/Test/ApiUnitTesting/ArchivosRequests/requests-2.10.0
- sudo python setup.py install
- cd ..
- python prueba.py

#- cd Appserver
#- mkdir build
#- cd build
#- cmake ..
#- make
#- cd ../Test
#- sh ./correr_pruebas_API.sh
- cd ../../../../../
- sh ./correrUnitTests.sh
