#install:
#  - sudo pip install requests
#language: php
#php:
#  - 5.5
#script: phpunit Test.php


sudo: required

services:
  - docker


before_install:
- docker pull juanmafc/appserver
- docker run -i -t -p 5000:5000 juanmafc/appserver /bin/sh -c "cd /home/taller2-appserver/Appserver/; git pull;"

script:
- cd /home/taller2-appserver/Appserver/build
- rm -r *
- cmake ..
- make
- cd ../Test
- ./correr_pruebas_API.sh
- ./correrUnitTests.sh
