#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

ls
echo "Pre commit"

cd Appserver
rm -r build
mkdir build
cd build
cmake ..
make
cd ../Test
rm -r ApiUnitTesting/EntornoDeTesting
mkdir ApiUnitTesting/EntornoDeTesting
sh ./correr_pruebas_API.sh
salidaPruebasAPI=$?
find . -name "*.pyc" -exec rm -rf {} \;
sh ./correrUnitTests.sh
salidaUnitTests=$?
exit $(($salidaPruebasAPI + $salidaUnitTests))
